M48
; DRILL file {KiCad (6.0.11-0)} date Friday, 15 September 2023 at 21:28:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-15T21:28:00+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C3.250
%
G90
G05
T1
X135.8Y-46.4
X140.2Y-46.4
X153.8Y-46.4
X158.2Y-46.4
T2
X98.55Y-80.9
X98.55Y-103.3
T3
X73.446Y-55.494
T4
X189.16Y-135.603
X216.56Y-135.603
T5
X74.0Y-44.0
X74.0Y-136.0
X226.0Y-44.0
X226.0Y-136.0
T6
X81.206Y-113.787
X81.206Y-125.217
T0
M30
